// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGBTTRruToyDVZFTBoukqdTdI_7ASxENA',
    appId: '1:721727257790:web:efec3830fb2d054bcef2ef',
    messagingSenderId: '721727257790',
    projectId: 'batteri-voltas77-b7161',
    authDomain: 'batteri-voltas77-b7161.firebaseapp.com',
    storageBucket: 'batteri-voltas77-b7161.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYjNsUVRgzbdOkXhSbciu-W6rncYH0Otg',
    appId: '1:721727257790:android:3b846ab39a017086cef2ef',
    messagingSenderId: '721727257790',
    projectId: 'batteri-voltas77-b7161',
    storageBucket: 'batteri-voltas77-b7161.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGBTTRruToyDVZFTBoukqdTdI_7ASxENA',
    appId: '1:721727257790:web:ac2d1153b7d97fbdcef2ef',
    messagingSenderId: '721727257790',
    projectId: 'batteri-voltas77-b7161',
    authDomain: 'batteri-voltas77-b7161.firebaseapp.com',
    storageBucket: 'batteri-voltas77-b7161.firebasestorage.app',
  );
}
